learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views

# TEMPLATE TAGGING
app_name = 'basic_app'

urlpatterns= [
    path('relative', views.relative,name='relative'),
    path('other',views.other,name='other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('basic_app/', include('basic_app.urls')),
    path('admin/', admin.site.urls),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world','number':100}
    return render(request, 'basic_app/index.html',context_dict)

def other(request):
    return render(request, 'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_temp.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>

  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <nav class="nav nav-pills">
      <div class="container">
        <ul class="nav nav-pills">
          <li><a class="nav-link active" href="{% url 'index' %}">BRAND</a></li>
          <li><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="nav-link" href="{% url 'basic_app:other' %}">Other</a></li>

        </ul>

      </div>

    </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}

    <h1>Welcome to Index!</h1>
    <h1>This is index.html page showing!</h1>

    <h1>{{ text|cut:'world' }}</h1>
    <h1>{{ number|add:"99" }}</h1>

  {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}

    <h1>Welcome to Other!</h1>
    <h2>This is an example of template inheritance!</h2>
    {% endblock %}

learning_templates/templates/basic_app/relative_url_temp.html
<!DOCTYPE html>

  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to relative URL Templates</h1>
    <a href="{% url 'basic_app:other' %}">The Other Page</a>
    <a href="{% url 'admin:index' %}">Admin Page</a>
    <a href="{% url 'index'}">Link to index</a>

  </body>
</html>